'use client';
import {forwardRef,useEffect} from'react';import type{ButtonHTMLAttributes,InputHTMLAttributes,ReactNode,SelectHTMLAttributes,TextareaHTMLAttributes}from'react';import{Loader2,X}from'lucide-react';
type Variant='primary'|'quiet'|'ghost'|'danger'|'sunset';const variants:Record<Variant,string>={primary:'bg-brand text-white border-transparent hover:bg-brand-hover active:scale-[0.99] shadow-xs shadow-brand/20',sunset:'bg-sunset text-white border-transparent hover:bg-[#b03808] active:scale-[0.99] shadow-xs shadow-sunset/20',quiet:'bg-surface text-ink border-rule hover:bg-canvas-subtle hover:border-gray-300 active:scale-[0.99]',ghost:'bg-transparent text-slate border-transparent hover:bg-sunk hover:text-ink',danger:'bg-surface text-flag border-flag/30 hover:bg-flag-soft'};
interface ButtonProps extends ButtonHTMLAttributes<HTMLButtonElement>{variant?:Variant;size?:'sm'|'md'|'lg';busy?:boolean}
export function Button({variant='quiet',size='md',busy,className='',children,...rest}:ButtonProps){const pad=size==='sm'?'min-h-9 px-3 text-[13px] rounded-[8px]':size==='lg'?'min-h-11 px-5 text-[15px] rounded-[12px]':'min-h-10 px-3.5 text-[14px] rounded-[10px]';return <button {...rest} disabled={rest.disabled||busy} className={`inline-flex items-center justify-center gap-2 border font-medium cursor-pointer transition-all duration-150 focus-visible:ring-2 focus-visible:ring-brand/30 disabled:opacity-50 disabled:cursor-not-allowed ${pad} ${variants[variant]} ${className}`}>{busy&&<Loader2 size={15} className="animate-spin"/>}{children}</button>}
export function Label({children,hint}:{children:ReactNode;hint?:string}){return <span className="mb-1.5 flex items-baseline justify-between gap-3"><span className="text-[13px] font-semibold text-ink">{children}</span>{hint&&<span className="eyebrow">{hint}</span>}</span>}
export const Input=forwardRef<HTMLInputElement,InputHTMLAttributes<HTMLInputElement>>(({className='',...rest},ref)=><input ref={ref}{...rest}className={`field ${className}`}/>);Input.displayName='Input';
export const Textarea=forwardRef<HTMLTextAreaElement,TextareaHTMLAttributes<HTMLTextAreaElement>>(({className='',...rest},ref)=><textarea ref={ref}{...rest}className={`field resize-y min-h-[90px] ${className}`}/>);Textarea.displayName='Textarea';
export const Select=forwardRef<HTMLSelectElement,SelectHTMLAttributes<HTMLSelectElement>>(({className='',...rest},ref)=><select ref={ref}{...rest}className={`field appearance-none bg-no-repeat pr-9 cursor-pointer ${className}`} style={{backgroundImage:"url(\"data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='12' height='8' viewBox='0 0 12 8'%3E%3Cpath d='M1 1.5l5 5 5-5' stroke='%234B5563' stroke-width='1.5' fill='none' stroke-linecap='round' stroke-linejoin='round'/%3E%3C/svg%3E\")",backgroundPosition:'right 12px center'}}/>);Select.displayName='Select';
export function Fieldset({label,hint,children}:{label:string;hint?:string;children:ReactNode}){return <label className="block"><Label hint={hint}>{label}</Label>{children}</label>}
export function Badge({tone,children}:{tone?:{fg:string;bg:string};children:ReactNode}){return <span className="inline-flex items-center rounded-full px-2.5 py-0.5 text-[11.5px] font-semibold tracking-tight" style={tone?{color:tone.fg,background:tone.bg}:{color:'var(--color-slate)',background:'var(--color-sunk)'}}>{children}</span>}
export function Notice({tone='flag',children}:{tone?:'flag'|'sand'|'sea';children:ReactNode}){const tones={flag:'bg-flag-soft text-flag border-flag/25',sand:'bg-sand-soft text-sand border-sand/25',sea:'bg-sea-soft text-sea border-sea/25'};return <div role="status" className={`rounded-[10px] border px-3.5 py-2.5 text-[13px] font-medium ${tones[tone]}`}>{children}</div>}
export function Spinner({label='Loading'}:{label?:string}){return <div role="status" aria-live="polite" className="flex flex-col items-center gap-2.5 py-16 justify-center text-slate"><Loader2 size={24} className="animate-spin text-brand"/><span className="eyebrow tracking-widest">{label}</span></div>}
export function Empty({title,body,action}:{title:string;body:string;action?:ReactNode}){return <div className="card flex flex-col items-center gap-3.5 px-6 py-14 text-center border-dashed border-gray-300"><div className="flex h-14 w-14 items-center justify-center rounded-full bg-brand-soft text-brand" aria-hidden><span className="text-2xl">✦</span></div><div><h3 className="text-lg font-bold text-ink">{title}</h3><p className="mt-1 max-w-sm text-[13.5px] text-slate">{body}</p></div>{action&&<div className="mt-1">{action}</div>}</div>}
export function Modal({open,onClose,title,children,wide}:{open:boolean;onClose:()=>void;title:string;children:ReactNode;wide?:boolean}){useEffect(()=>{if(!open)return;const onKey=(e:KeyboardEvent)=>{if(e.key==='Escape')onClose()};document.addEventListener('keydown',onKey);return()=>document.removeEventListener('keydown',onKey)},[open,onClose]);if(!open)return null;return <div className="fixed inset-0 z-50 flex items-center justify-center p-4"><div className="fixed inset-0 bg-black/40 backdrop-blur-xs" onClick={onClose} aria-hidden/><div role="dialog" aria-modal="true" aria-label={title} className={`rise relative z-10 max-h-[calc(100dvh-2rem)] w-full overflow-auto rounded-[16px] border bg-surface p-6 shadow-2xl ${wide?'max-w-2xl':'max-w-lg'}`}><div className="mb-4 flex items-center justify-between border-b pb-3.5"><h2 className="text-[19px] font-bold text-ink">{title}</h2><button onClick={onClose} className="rounded-full p-2 text-slate hover:bg-sunk hover:text-ink focus-visible:ring-2 focus-visible:ring-brand" aria-label="Close"><X size={18}/></button></div>{children}</div></div>}
export function SkeletonCard(){return <div className="card overflow-hidden animate-pulse"><div className="aspect-[16/10] bg-sunk"/><div className="p-4 space-y-2.5"><div className="h-4 w-3/4 bg-sunk rounded-md"/><div className="h-3 w-1/2 bg-sunk rounded-md"/><div className="h-3 w-1/3 bg-sunk rounded-md"/></div></div>}
export function SkeletonTimeline(){return <div className="space-y-4 animate-pulse">{[1,2,3].map(i=><div key={i} className="card p-5 space-y-3"><div className="h-5 w-1/3 bg-sunk rounded-md"/><div className="h-4 w-1/2 bg-sunk rounded-md"/><div className="h-12 w-full bg-sunk rounded-lg"/></div>)}</div>}
