import { Types } from 'mongoose';
import { connectMongo } from './db';
import { City, Activity, Trip } from './models';
import { dayCount, tripStatus } from './helpers';

export async function resolveId(model:any, id:string|number) { await connectMongo(); if (Types.ObjectId.isValid(String(id))) return new Types.ObjectId(String(id)); const doc=await model.findOne({legacyId:Number(id)}).select('_id').lean(); if(!doc) throw new Error('Referenced document not found.'); return doc._id; }
export const idOf=(d:any):string|number=>d?.legacyId ?? String(d?._id);
export const userDto=(u:any)=>({id:idOf(u),first_name:u.firstName,last_name:u.lastName,email:u.email,phone:u.phone??null,city:u.city??null,country:u.country??null,bio:u.bio??null,photo_url:u.photoUrl??null,language:u.language??'en',home_currency:u.homeCurrency??'USD',role:u.role,created_at:u.createdAt});
export const cityDto=(c:any,count?:number)=>({id:idOf(c),name:c.name,country:c.country,region:c.region,cost_index:c.costIndex,popularity:c.popularity,currency:c.currency,image_url:c.imageUrl??null,description:c.description??null,...(count===undefined?{}:{activity_count:count})});
export const activityDto=(a:any,c?:any)=>({id:idOf(a),city_id:idOf(c??a.city),name:a.name,category:a.category,cost:a.cost,duration_minutes:a.durationMinutes,description:a.description??null,popularity:a.popularity,city_name:c?.name,country:c?.country});
export function tripDto(t:any, owner?:any){const stops=(t.stops??[]).slice().sort((a:any,b:any)=>a.position-b.position).map((s:any)=>{const c=s.city as any;const activities=(s.activities??[]).slice().sort((a:any,b:any)=>a.scheduledDate.localeCompare(b.scheduledDate)||a.position-b.position).map((a:any)=>({id:idOf(a),trip_id:idOf(t),stop_id:idOf(s),activity_id:a.activity?String(a.activity):null,title:a.title,category:a.category,cost:a.cost,scheduled_date:a.scheduledDate,start_time:a.startTime??null,duration_minutes:a.durationMinutes,position:a.position,notes:a.notes??null}));return{id:idOf(s),trip_id:idOf(t),city_id:idOf(c),city_name:c?.name??'',country:c?.country??'',region:c?.region??'',cost_index:c?.costIndex??0,start_date:s.startDate,end_date:s.endDate,position:s.position,nights:Math.max(0,dayCount(s.startDate,s.endDate)-1),notes:s.notes??null,activities};});const costs=(t.costs??[]).map((c:any)=>({id:idOf(c),trip_id:idOf(t),stop_id:c.stop?String(c.stop):null,category:c.category,label:c.label,amount:c.amount}));const travellers=Math.max(1,t.travellers||1);const activityTotal=stops.flatMap((s:any)=>s.activities).reduce((n:number,a:any)=>n+Number(a.cost)*travellers,0);const total=costs.reduce((n:number,c:any)=>n+Number(c.amount),0)+activityTotal;const days=dayCount(t.startDate,t.endDate);return{...t,id:idOf(t),user_id:idOf(t.user),name:t.name,description:t.description??null,start_date:t.startDate,end_date:t.endDate,cover_url:t.coverUrl??null,travellers,is_public:t.isPublic?1:0,share_slug:t.shareSlug??null,status:tripStatus(t.startDate,t.endDate),days,owner_name:owner?`${owner.firstName} ${owner.lastName}`.trim():undefined,stops,costs,route:stops.map((s:any)=>({id:s.id,city:s.city_name,country:s.country})),budget:{total,days,travellers,averagePerDay:Math.round(total/days),dailyAverage:0,byStop:[],perTraveller:Math.round(total/travellers),breakdown:[],daily:[],threshold:0,heavyDays:[]}};}
export { City, Activity, Trip };
