import { connectMongo } from './db';
import { Trip, User } from './models';
import { notFound, dayCount, tripStatus } from './helpers';
import { tripDto, resolveId } from './mongo';
import type { Budget, Trip as TripType } from './types';

export async function loadTrip(tripId:string|number):Promise<TripType>{await connectMongo();const id=await resolveId(Trip,tripId);const trip=await Trip.findById(id).populate('user','firstName lastName photoUrl').populate('stops.city').lean();if(!trip)throw notFound('That trip does not exist.');return tripDto(trip,trip.user) as TripType;}
export function budgetFor(trip:any,stops:any[],activities:any[],costs:any[]):Budget{const travellers=Math.max(1,trip.travellers||1);const entered:any={transport:0,stay:0,meals:0,other:0};for(const c of costs)entered[c.category]=(entered[c.category]||0)+Number(c.amount);const total=Math.round(Object.values(entered).reduce((a:any,b:any)=>a+b,0)+activities.reduce((n:number,a:any)=>n+Number(a.cost)*travellers,0));const days=dayCount(trip.startDate??trip.start_date,trip.endDate??trip.end_date);return{total,days,travellers,averagePerDay:Math.round(total/days),dailyAverage:0,byStop:[],perTraveller:Math.round(total/travellers),breakdown:Object.entries(entered).filter(([,amount])=>Number(amount)>0).map(([category,amount])=>({category,amount:Number(amount),estimated:false})),daily:[],threshold:0,heavyDays:[]};}
export async function listTrips(userId:string|number):Promise<TripType[]>{await connectMongo();const uid=await resolveId(User,userId);const docs=await Trip.find({user:uid}).sort({startDate:-1}).populate('user','firstName lastName photoUrl').populate('stops.city').lean();return docs.map((d:any)=>tripDto(d,d.user) as TripType);}
export async function ownedTrip(tripId:string|number,userId:string|number){await connectMongo();const tid=await resolveId(Trip,tripId);const uid=await resolveId(User,userId);const trip=await Trip.findOne({_id:tid,user:uid}).lean();if(!trip)throw notFound('That trip does not exist.');return trip;}
